
// This file has been generated by the GUI designer. Do not modify.
namespace sharptalk
{
	public partial class UserDialog
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Image image2;
		private global::Gtk.Label label1;
		private global::Gtk.Label labelNumPosts;
		private global::Gtk.Label labelLastActivity;
		private global::Gtk.Label label3;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget sharptalk.UserDialog
			this.Name = "sharptalk.UserDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("User Information");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child sharptalk.UserDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.fixed1.Add (this.image2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.image2]));
			w2.X = 12;
			w2.Y = 16;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of posts:");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w3.X = 98;
			w3.Y = 34;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelNumPosts = new global::Gtk.Label ();
			this.labelNumPosts.Name = "labelNumPosts";
			this.fixed1.Add (this.labelNumPosts);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.labelNumPosts]));
			w4.X = 220;
			w4.Y = 34;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.labelLastActivity = new global::Gtk.Label ();
			this.labelLastActivity.Name = "labelLastActivity";
			this.fixed1.Add (this.labelLastActivity);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.labelLastActivity]));
			w5.X = 220;
			w5.Y = 58;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Last Activity:");
			this.fixed1.Add (this.label3);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
			w6.X = 100;
			w6.Y = 58;
			w1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1 [this.fixed1]));
			w7.Position = 0;
			// Internal child sharptalk.UserDialog.ActionArea
			global::Gtk.HButtonBox w8 = this.ActionArea;
			w8.Name = "dialog1_ActionArea";
			w8.Spacing = 10;
			w8.BorderWidth = ((uint)(5));
			w8.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "Close";
			this.AddActionWidget (this.buttonOk, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.buttonOk]));
			w9.Expand = false;
			w9.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
