
// This file has been generated by the GUI designer. Do not modify.
namespace sharptalk
{
	public partial class ForumAdd
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Entry entryForumUsername;
		private global::Gtk.Entry entryForumPassword;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.CheckButton checkbutton1;
		private global::Gtk.Entry entryForumUrl;
		private global::Gtk.Label label1;
		private global::Gtk.Label label4;
		private global::Gtk.Entry entryForumName;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget sharptalk.ForumAdd
			this.Name = "sharptalk.ForumAdd";
			this.Title = global::Mono.Unix.Catalog.GetString ("Add Forum");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child sharptalk.ForumAdd.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryForumUsername = new global::Gtk.Entry ();
			this.entryForumUsername.WidthRequest = 210;
			this.entryForumUsername.CanFocus = true;
			this.entryForumUsername.Name = "entryForumUsername";
			this.entryForumUsername.IsEditable = true;
			this.entryForumUsername.InvisibleChar = '●';
			this.fixed1.Add (this.entryForumUsername);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryForumUsername]));
			w2.X = 12;
			w2.Y = 164;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryForumPassword = new global::Gtk.Entry ();
			this.entryForumPassword.WidthRequest = 210;
			this.entryForumPassword.CanFocus = true;
			this.entryForumPassword.Name = "entryForumPassword";
			this.entryForumPassword.IsEditable = true;
			this.entryForumPassword.InvisibleChar = '●';
			this.fixed1.Add (this.entryForumPassword);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryForumPassword]));
			w3.X = 243;
			w3.Y = 164;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Username:");
			this.fixed1.Add (this.label2);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
			w4.X = 12;
			w4.Y = 144;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Password:");
			this.fixed1.Add (this.label3);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
			w5.X = 243;
			w5.Y = 144;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.checkbutton1 = new global::Gtk.CheckButton ();
			this.checkbutton1.CanFocus = true;
			this.checkbutton1.Name = "checkbutton1";
			this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString ("Authenticate");
			this.checkbutton1.DrawIndicator = true;
			this.checkbutton1.UseUnderline = true;
			this.fixed1.Add (this.checkbutton1);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkbutton1]));
			w6.X = 12;
			w6.Y = 116;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryForumUrl = new global::Gtk.Entry ();
			this.entryForumUrl.WidthRequest = 440;
			this.entryForumUrl.CanFocus = true;
			this.entryForumUrl.Name = "entryForumUrl";
			this.entryForumUrl.IsEditable = true;
			this.entryForumUrl.InvisibleChar = '●';
			this.fixed1.Add (this.entryForumUrl);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryForumUrl]));
			w7.X = 12;
			w7.Y = 84;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Forum URL:");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w8.X = 12;
			w8.Y = 64;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Forum Name:");
			this.fixed1.Add (this.label4);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
			w9.X = 12;
			w9.Y = 10;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryForumName = new global::Gtk.Entry ();
			this.entryForumName.WidthRequest = 210;
			this.entryForumName.CanFocus = true;
			this.entryForumName.Name = "entryForumName";
			this.entryForumName.IsEditable = true;
			this.entryForumName.InvisibleChar = '●';
			this.fixed1.Add (this.entryForumName);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryForumName]));
			w10.X = 12;
			w10.Y = 30;
			w1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1 [this.fixed1]));
			w11.Position = 0;
			// Internal child sharptalk.ForumAdd.ActionArea
			global::Gtk.HButtonBox w12 = this.ActionArea;
			w12.Name = "dialog1_ActionArea";
			w12.Spacing = 10;
			w12.BorderWidth = ((uint)(5));
			w12.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12 [this.buttonCancel]));
			w13.Expand = false;
			w13.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12 [this.buttonOk]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 474;
			this.DefaultHeight = 268;
			this.Show ();
			this.checkbutton1.Toggled += new global::System.EventHandler (this.checkbutton1_Toggled);
		}
	}
}
