
// This file has been generated by the GUI designer. Do not modify.
namespace sharptalk
{
	public partial class MessageView
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget sharptalk.MessageView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "sharptalk.MessageView";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
